### ISSUE TITLE
HTML report files in wrong location

### ISSUE THREAD

**Issue by dustinmartin** [SitePen/remap-istanbul#49] opened 2016-04-26 16:13 UTC
For some reason, when I run the remap task it outputs the generated HTML files in three separate folders. Though the links between the files work, the CSS, JS, and other assets can't be found.

Here is what I'm seeing:

![code](https://cloud.githubusercontent.com/assets/141065/14825493/ce06dd74-0b9f-11e6-8d4c-67a53f30def4.png)

Notice `coverage/original` has the original Istanbul output. That works great.

`coverage/remapped` has the output from `remapIstanbul`.

The arrows point to the three separate locations that the generated files get output too.

Here is the relevant portion of my Gruntfile:

```
    mocha_istanbul: {
      coverage: {
        src: files.tests,
        options: {
          coverageFolder: 'coverage/original/',
          recursive: true,
          timeout: 20000,
          reporter: 'spec'
        }
      }
    },
    remapIstanbul: {
      build: {
        src: 'coverage/original/coverage.json',
        options: {
          reports: {
            html: 'coverage/remapped/html-report/',
            json: 'coverage/remapped/coverage-final.json'
          }
        }
      }
    },
```

I'd love to see everything output to `coverage/remapped/html-report/src` but I'm not sure what is going on. Any ideas?

**Comment by kitsonk** [comment] 2016-04-26 18:14
It it at all possible to get a view of the `coverage.json`?

**Comment by dustinmartin** [comment] 2016-04-26 18:43
Sure thing. Here is a link that has the original coverage file as well as the remapped version (coverage-final).

https://www.evernote.com/l/AAO-PNrlYMtJoJxGsS9NSvLa4xLc_g4t0O4

**Comment by dustinmartin** [comment] 2016-04-28 15:30
@kitsonk Any update on this?

**Comment by Protectator** [comment] 2016-05-03 15:31
Ain't this the same problem as #50 ?

**Comment by dylans** [comment] 2017-01-11 12:47
I believe this is a duplicate of #50.

**Closed by dylans** 2017-01-11 12:47 UTC
Labels: bug
